name: llm-examples
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - python-dotenv
  - jupyterlab
  - jupyter-dash
  - requests
  - ipython
  - pip:
    - ollama
    - beautifulsoup4
